// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcBhrI_JhMHZ0Eqm4gUycKBkYHtq1cdVs',
    appId: '1:344280049106:web:317b146cdb3d97f968d40b',
    messagingSenderId: '344280049106',
    projectId: 'xusemeapp',
    authDomain: 'xusemeapp.firebaseapp.com',
    storageBucket: 'xusemeapp.appspot.com',
    measurementId: 'G-LVVPB45SE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkv42R2T73tUAJAgs_hqWqx_jN-KY6Sm0',
    appId: '1:344280049106:android:b816c251955ef2d668d40b',
    messagingSenderId: '344280049106',
    projectId: 'xusemeapp',
    storageBucket: 'xusemeapp.appspot.com',
  );
}
